### ISSUE TITLE
non-cartesian MRSI

### ISSUE THREAD

**Issue by brendo-k** [wtclarke/mrs_nifti_standard#4]
HI William, 

I am a developer for FID-A and we're working on a MRSI processing pipeline and we're interesting in incorporating nifti-MRS and nifti-MRSI. I want to build importing tools for non-cartesian MRSI and I was wondering if there was a standard? We currently hold non-cartesian MRSI data in (time Dimension, numTR) which we can upload to nifit's 4th and 5th dimension. 

Best, 
Brenden

**Comment by wtclarke** [comment]
Hi Brendan,

I think you should look at the [ISMRMRD](https://github.com/ismrmrd/ismrmrd) format if you are interested in storing raw, unreconstructed k(t)-space data. NIfTI only makes sense for data that appears on a rectilinear image-space grid, i.e. after reconstruction. Non-cartesian data requires a lot of sequence specific knowledge to reconstruct, and NIfTI can't contain that (ISMRMRD does have e.g. trajectory fields).

However, once reconstructed, it would certainly make sense to hold your data in NIfTI-MRS format, which is fine for further pre-processing (e.g. coil combination). Happy to offer insight into how to do that, though I think Georg had done some work on that in FID-A for Osprey.

**Comment by brendo-k** [comment]
HI William, 

Thank you for the info! I will definitely be adding nifti-mrsi and nifti-mrs export for FID-A!
