### ISSUE TITLE
AcqusitionStartTime → AcquisitionStartTime

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [wtclarke/mrs_nifti_standard#5]
Is it still time to fix that typo in [5.1 MRS specific tags](https://github.com/wtclarke/mrs_nifti_standard/blob/master/specification.MD#51-mrs-specific-tags)?

<table>
  <colgroup>
    <col width="20%">
    <col width="20%">
    <col width="10%">
    <col width="50%">
  </colgroup>
  <tr>
   <td><strong>Key</strong></td>
   <td><strong>Datatype</strong></td>
   <td><strong>Unit</strong></td>
   <td><strong>Description</strong></td>
   <td><strong>Anon (Y/N)</strong></td>
  </tr>
  <tr>
   <td><strike>AcqusitionStartTime</strike><br/>AcquisitionStartTime</td>
   <td>number</td>
   <td>s</td>
   <td>Time, relative to EchoTime, that the acquisition starts. Positive values indicate a time after the EchoTime, negative indicate before the EchoTime, a value of zero indicates no offset. Units: Seconds</td>
   <td>N</td>
  </tr>

</table>

**Comment by wtclarke** [comment]
Thanks, fixed in V0.6.0.
